matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8.3
script:
  - set -o pipefail
  - xcodebuild test -scheme TypedRouter -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty -c
